In [1]:
import requests
import re
import pandas as pd
import datetime

In [2]:
fecha = str(datetime.date.today())
print(fecha)

2020-12-13

In [3]:
url = 'https://datos.covid-19.conacyt.mx/Overview/info/getInfo.php'

In [4]:
DF_temp = pd.read_excel("../data-validation/bitacora_historica_tablero_oficial.xlsx")
DF_temp

,Fecha,Confirmados,Negativos,Sospechosos,Defunciones,Porcentaje hospitalizados
0,2020-06-01,93435,150157,38497,10167,34.90
1,2020-06-02,97326,153601,42151,10637,34.59
2,2020-06-03,101238,157354,44869,11728,34.45
3,2020-06-04,105680,161724,46659,12545,34.24
4,2020-06-05,110026,166049,48822,13170,34.03
...,...,...,...,...,...,...
151,2020-12-08,1193255,1472266,388192,110874,21.06
152,2020-12-09,1205229,1490180,391101,111655,20.98
153,2020-12-10,1217126,1507203,393908,112326,20.90
154,2020-12-11,1229379,1525914,395511,113019,20.80
155,2020-12-12,1241436,1543802,397078,113704,20.71

In [5]:

value_1 = "Confirmados"
value_2 = "Negativos"
value_3 = "Sospechosos"
value_4 = "Defunciones"
value_5 = "Hospitalizados"

data = {
    "sPatType": {
        "key_1": value_1, 
        "key_2": value_2,
        "key_3": value_3,
        "key_4": value_4,
        "key_5": value_5,
    },
    "cve": "000",
    "nom": 'Nacional'
}

raw_data = requests.post(url, data=data).text
confirmados = int(re.search(r'document\.getElementById\("gsPosDIV"\)\.innerHTML = \((\d+)', raw_data).group(1))
negativos = int(re.search(r'document\.getElementById\("gsNegDIV"\)\.innerHTML = \((\d+)', raw_data).group(1))
sospechosos = int(re.search(r'document\.getElementById\("gsSosDIV"\)\.innerHTML = \((\d+)', raw_data).group(1))
defunciones = int(re.search(r'document\.getElementById\("gsDefDIV"\)\.innerHTML = \((\d+)', raw_data).group(1))
#hospitalizados = re.search(r'document\.getElementById\("vHos"\)\.innerHTML =  \\d+(?:\\.\\d+)?%', raw_data).group(1)
hospitalizados = 20.67

In [6]:
#Añadimos las tuplas siguientes
new_row3 = {'Fecha':fecha, 'Confirmados':confirmados,'Negativos':negativos, 'Sospechosos': sospechosos,
            'Defunciones': defunciones , "Porcentaje hospitalizados": hospitalizados}

DF_temp = DF_temp.append(new_row3, ignore_index = True)

In [8]:
DF_temp

,Fecha,Confirmados,Negativos,Sospechosos,Defunciones,Porcentaje hospitalizados
0,2020-06-01,93435,150157,38497,10167,34.90
1,2020-06-02,97326,153601,42151,10637,34.59
2,2020-06-03,101238,157354,44869,11728,34.45
3,2020-06-04,105680,161724,46659,12545,34.24
4,2020-06-05,110026,166049,48822,13170,34.03
...,...,...,...,...,...,...
152,2020-12-09,1205229,1490180,391101,111655,20.98
153,2020-12-10,1217126,1507203,393908,112326,20.90
154,2020-12-11,1229379,1525914,395511,113019,20.80
155,2020-12-12,1241436,1543802,397078,113704,20.71
156,2020-12-13,1250044,1553633,390587,113953,20.67

In [9]:
direccion = "../data-validation/"
DF_temp.to_excel(direccion +"bitacora_historica_tablero_oficial" + ".xlsx", sheet_name='out_vars',encoding="utf-8", index = False)