In [37]:
import requests
import re
import pandas as pd
import datetime

In [38]:
fecha = str(datetime.date.today())
print(fecha)

2020-12-07

In [39]:
url = 'https://datos.covid-19.conacyt.mx/Overview/info/getInfo.php'

In [40]:
DF_temp = pd.read_excel("../data-validation/bitacora_historica_tablero_oficial.xlsx")
DF_temp

,Fecha,Confirmados,Negativos,Sospechosos,Defunciones,Porcentaje hospitalizados
0,2020-06-01,93435,150157,38497,10167,34.900000
1,2020-06-02,97326,153601,42151,10637,34.590000
2,2020-06-03,101238,157354,44869,11728,34.450000
3,2020-06-04,105680,161724,46659,12545,34.240000
4,2020-06-05,110026,166049,48822,13170,34.030000
...,...,...,...,...,...,...
145,2020-10-23 00:00:00,880775,1058102,330956,88312,22.990548
146,2020-10-24 00:00:00,886800,1066646,335143,88743,22.937303
147,2020-10-25 00:00:00,891160,1072760,331758,88924,22.897796
148,2020-10-26,895326,1078072,328231,89171,22.890000
149,2020-10-27,901268,1086229,335517,89814,22.850000

In [41]:

value_1 = "Confirmados"
value_2 = "Negativos"
value_3 = "Sospechosos"
value_4 = "Defunciones"
value_5 = "Hospitalizados"

data = {
    "sPatType": {
        "key_1": value_1, 
        "key_2": value_2,
        "key_3": value_3,
        "key_4": value_4,
        "key_5": value_5,
    },
    "cve": "000",
    "nom": 'Nacional'
}

raw_data = requests.post(url, data=data).text
confirmados = int(re.search(r'document\.getElementById\("gsPosDIV"\)\.innerHTML = \((\d+)', raw_data).group(1))
negativos = int(re.search(r'document\.getElementById\("gsNegDIV"\)\.innerHTML = \((\d+)', raw_data).group(1))
sospechosos = int(re.search(r'document\.getElementById\("gsSosDIV"\)\.innerHTML = \((\d+)', raw_data).group(1))
defunciones = int(re.search(r'document\.getElementById\("gsDefDIV"\)\.innerHTML = \((\d+)', raw_data).group(1))
#hospitalizados = re.search(r'document\.getElementById\("vHos"\)\.innerHTML =  \\d+(?:\\.\\d+)?%', raw_data).group(1)
hospitalizados = 21.13

In [42]:
#Añadimos las tuplas siguientes
new_row3 = {'Fecha':fecha, 'Confirmados':confirmados,'Negativos':negativos, 'Sospechosos': sospechosos,
            'Defunciones': defunciones , "Porcentaje hospitalizados": hospitalizados}

DF_temp = DF_temp.append(new_row3, ignore_index = True)

In [43]:
DF_temp

,Fecha,Confirmados,Negativos,Sospechosos,Defunciones,Porcentaje hospitalizados
0,2020-06-01,93435,150157,38497,10167,34.900000
1,2020-06-02,97326,153601,42151,10637,34.590000
2,2020-06-03,101238,157354,44869,11728,34.450000
3,2020-06-04,105680,161724,46659,12545,34.240000
4,2020-06-05,110026,166049,48822,13170,34.030000
...,...,...,...,...,...,...
146,2020-10-24 00:00:00,886800,1066646,335143,88743,22.937303
147,2020-10-25 00:00:00,891160,1072760,331758,88924,22.897796
148,2020-10-26,895326,1078072,328231,89171,22.890000
149,2020-10-27,901268,1086229,335517,89814,22.850000
150,2020-12-07,1182249,1456073,384905,110074,21.130000

In [44]:
direccion = "../data-validation/"
DF_temp.to_excel(direccion +"bitacora_historica_tablero_oficial" + ".xlsx", sheet_name='out_vars',encoding="utf-8", index = False)